name: Android CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./src-mobile-app/gradlew build

  test_nunit:

    env: 
      working-directory: src-mobile-app
    
    runs-on: macos-latest
    #runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Execute unit tests
      run: ./gradlew test
      working-directory: ${{env.working-directory}}

  #android front-end tests      
  test_android:
    
    env: 
      working-directory: src-mobile-app
      
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      working-directory: ${{env.working-directory}}
    
    - name: Execute android front-end tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 23
        target: default
        arch: x86
        profile: Nexus 5X
        script: ./gradlew connectedCheck --stacktrace
        working-directory: ${{env.working-directory}}